### ISSUE TITLE
Consider lookahead implications of text format rules

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/module-types#6]
@alexcrichton pointed out two cases where we need 2 tokens of lookahead when parsing modules and module types (after #3) so I wanted to surface these to see if there's any nice alternatives (since it sounds like, until now, we've only needed 1 token of lookahead).  Otherwise, it seems fine?

1. After scanning the tokens `(` `module` `(` `export`, we need two more tokens to see if this `export` is declaring the containing module to be exported (as in `(module (export "foo"))`) or just the start of an export of this module (as in: `(module (export "foo" (func $f))`.

2. After scanning the tokens `(` `module` `(` `type`, we need two more tokens to see if this `type` is explicitly declaring the type of the containing module (as in `(module (type $t))`, symmetric to `(func (type $t) ...)` in the MVP) or the start of a type definition (as in `(module (type $t (func (param i32))))`).

**Comment by binji** [comment]
For 1) can we adjust the text syntax to be more symmetric with existing exports? e.g.:
```wat
(module
  ...
  (export "foo" (module))
)
```

Presumably this matches the binary format better too.

Not sure about 2), but the easy solution is to pick another keyword (e.g. `module_type`), though this is kind of ugly. That said, it makes some sense to have something different here, given that it's referencing a type from the outer module's scope.

**Comment by rossberg** [comment]
Hm, interesting. But I think it's all still LALR(1), since nothing has to be reduced before seeing the disambiguating tokens. Or am I missing something? It's not LL(1), but has the text format grammar been that before?

Not sure what a nice alternative would be. At least I can't think of anything that would be consistent with the rest of the syntax. (@binji, I don't understand your suggestion. The offending `(module (export "foo"))` case is the shorthand for `(module $m) (export "foo" (module $m))` in the _surrounding_ module.)

**Comment by alexcrichton** [comment]
FWIW this is technically also true for `import` as well, after seeing `(` `module` `(` `import` you'll need to do the same thing as `type` and `export`.

Also to be clear I don't think this is really a major problem or anything, it was just something that hadn't already come up when writing a text parser. The only alternative I could think of is to introduce a new form of construct like so:

```
(nested-module (module ...)
```

that way `(module ...)` is sugar for `(nested-module (module ...))` and inline `type`/`import`/`export` annotations could only be applied to `nested-module`:

```
(nested-module (type 3) (export "x") (import "") (module ...))
```

I don't think this is a good alternative though because the `(module` form is still quite reasonably parseable.

The main point I think is worth to acknowledge is that it can be visually confusing:

```
(module
  (type $foo) 
  (type $foo (func))
  ;; ...
)
```

I think that's still ok, however, because inline `(module ...` is quite convenient.

**Comment by rossberg** [comment]
> ```
> (module
>   (type $foo) 
>   (type $foo (func))
>   ;; ...
> )
> ```

Interesting, should we even allow that? We have such a mixture for function type uses, but does it make sense for modules? I guess it does, to be able to explicitly select a type index.

I would probably format the above as
```
(module (type $foo)
  (type $foo (func))
  ;; ...
)
```
to make the different roles clearer. Still, I agree that the use of `type` for both definition and use sites bytes us a bit now.

**Comment by alexcrichton** [comment]
I do think that we'll need to have some way of specifying "this module has this type index" so a binary-to-text printer can produce something which, when parsed, doesn't automatically inject a new `type` declaration. I think it's effectively required for round-trip-ability.

Also yeah I don't think that you'd ever want to format the `(type $foo)` on its own line since it looks so similar to type declarations, I think conventionally inline type/export/import annotations would probably all be on the same line as the `(module` directive, same with the module's name and such.

**Comment by rossberg** [comment]
Yes, makes sense.

**Comment by binji** [comment]
> (@binji, I don't understand your suggestion. The offending (module (export "foo")) case is the shorthand for (module $m) (export "foo" (module $m)) in the surrounding module.)

Yeah, I misunderstood. Sorry! Let me see if I understand correctly: these constructs are the same as we have for func/table/global/etc. right? e.g. `(table (export "t") ...)` or `(func (import "a" "b") ...)`. We could require an additional token (`desc` say) surrounding these definitions, which is normally optional but required for `module`:

```wat
(module
  ;; module desc block
  (desc (type 0) (export "foo"))
  ...
  ;; func desc block
  (func (desc (type 0) (export "f")) ...)
)
```

**Comment by lukewagner** [comment]
Actually, I wonder if we have an ambiguity at some point in our future with `(type $T)` (where `$T` can either be the identifier of a *new* type being defined or a reference to an *existing* type definition index.

We could perhaps rule out this ambiguity by saying: when you define a type, there will always be some token after the identifier before the `)`, but I wonder if this will always be true.

One possible counter-example I remember is: what's the instance type of a module:
```wasm
(module
  (type (import "foo") $T)
  (func (export "bar" (param (ref $T)) ...)
)
```
Noting that `$T` is not itself an exported type, we talked about maybe writing something like:
```wasm
(instance
  (type $T)
  (func (export "bar") (param (ref $T)))
)
```

It seems like, in retrospect, it would've been better to use a different token for type uses; maybe it's not too late to change...?

**Comment by rossberg** [comment]
> It seems like, in retrospect, it would've been better to use a different token for type uses; maybe it's not too late to change...?

Yes, indeed. But what?

Note also that we don't just have type uses, with bulk instructions we also introduce analogous syntax for table and memory uses (in segment definitions). And the occurrences in exports are arguably related as well.

**Comment by lukewagner** [comment]
Yeah, no easy answer.  Thinking about this again, it's probably far too late to consider changing basic MVP text syntax, anyhow, so let me retract that.

I think maybe the solution is just to say that, now and henceforth, we'll distinguish type uses from type definitions by the presence of at least one initializer token `(type $id **here**)`.  For the avoidance problem mentioned above, maybe the answer is we just don't end up needing to allow writing the type of such modules/instances as closed expressions in the text format?

**Comment by rossberg** [comment]
> we'll distinguish type uses from type definitions by the presence of at least one initializer token `(type $id **here**)`

Yes, I think this rule should universally apply to all definitions/declarations: they always have some right-hand side. So maybe in the case of declaring an existential type in an instance type you'll always need to give a bound explicitly, such as `(type $t any)` (I do think that you'll occasionally need the ability to write such types in the text format).

**Comment by lukewagner** [comment]
Ok, then I think we're good here.  I'll resolve now since I opened the issue, but anyone feel free to reopen if there's more to discuss.
